[mongo_servers]
#prod env
smdb001.hay01.gdaas.com mongod_port=27017 ansible_user=root
smdb002.hay01.gdaas.com mongod_port=27017 ansible_user=root
smdb003.hay01.gdaas.com mongod_port=27017 ansible_user=root

[mongod_primary]
#prod env
smdb001.hay01.gdaas.com mongod_port=27017 ansible_user=root

[mongod_slaves]
#prod env
smdb002.hay01.gdaas.com mongod_port=27017 ansible_user=root
smdb003.hay01.gdaas.com mongod_port=27017 ansible_user=root